### 1

In [2]:
import numpy as np

In [3]:
n= int(input())

5


In [4]:
matrix = np.identity(n, dtype=np.int8)

In [5]:
print(matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [6]:
for i in range(n):
    for j in range(n):
        matrix[i][j]=(i+j)%2

In [7]:
matrix

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]], dtype=int8)

### 2

In [8]:
x1= int(input())
y1= int(input())
z1= int(input())
x2= int(input())
y2= int(input())
z2= int(input())

1
2
3
4
5
6


In [9]:
sc = np.dot(np.array([x1, y1, z1]), np.array([x2, y2, z2]))
print("scalar: ", sc)

scalar:  32


In [10]:
ve = np.cross(np.array([x1, y1, z1]), np.array([x2, y2, z2]))
print ("vector:", ve)

vector: [-3  6 -3]


In [11]:
def len(a):
    return np.sqrt(a[0]*a[0]+a[1]*a[1]+a[2]*a[2])

In [12]:
print ("by scalar angle = ", np.degrees(np.arccos(sc/(len([x1, y1, z1])*len([x2, y2, z2])))))

by scalar angle =  12.933154491899135


In [13]:
print ("by vector angle = ", np.degrees(np.arcsin(len(ve)/(len([x1, y1, z1])*len([x2, y2, z2])))))

by vector angle =  12.93315449189912


### 3

In [14]:
import random

In [23]:
m1 = np.full(shape =(4, 4), fill_value =int(random.random()*100))
m2 = np.full(shape =(4, 4), fill_value =int(random.random()*100))

In [29]:
m1,m2=m2,m1
for i in range(4):
    for j in range(4):
        m1[i][j]=(m1[i][j]*int(random.random()*100))%100
        m2[i][j]=(m2[i][j]*int(random.random()*100))%100
print(m1)
print(m2)

[[ 0 12 56 12]
 [52 48  0 40]
 [96 44 92 80]
 [24 80 92 16]]
[[50 28 56 20]
 [36 60 44 56]
 [36 44 48 84]
 [56  0 40 30]]


In [36]:
arr1 = np.ravel(m1)
arr2 = np.ravel(m2)

[ 0 12 56 12 52 48  0 40 96 44 92 80 24 80 92 16] [50 28 56 20 36 60 44 56 36 44 48 84 56  0 40 30]


In [38]:
res = {i for i in arr1 if np.isclose(arr2, i, 0.0001).any()}
print(res)

{0, 40, 44, 48, 56}


### 4

In [40]:
b=m2[0]
a=m1
print(np.linalg.solve(a, b))

[-2.88362205  0.36433127 -0.04482338  4.01151115]
